
INSERT INTO users VALUES (default, "Saul", "1234", "user");
INSERT INTO events VALUES (default,1, "2023-02-17", "Tenia los ojitos ratoniles, maliciosos. Sabia dilatarlos duramente o desmayarlos con recato o levantarlos con disimulo. Caminaba contoneando las imposibles caderas y era difícil, al verla.", "https://images.ecestaticos.com/5HaHadOJGkVz15_G8qObVeZE7kE=/199x0:999x599/1200x900/filters:fill(white):format(jpg)/f.elconfidencial.com%2Foriginal%2F99a%2Fdbc%2F18a%2F99adbc18a4237d4a5d9ce60187b4f698.jpg", 30, 0, "Concierto");
INSERT INTO events VALUES (default,1, "2023-02-17", "Tenia los ojitos ratoniles, maliciosos. Sabia dilatarlos duramente o desmayarlos con recato o levantarlos con disimulo. Caminaba contoneando las imposibles caderas y era dificil, al verla.", "https://image.shutterstock.com/image-vector/hackathon-concept-icon-set-big-260nw-2019732209.jpg", 30, 0, "Hackaton");
INSERT INTO events VALUES (default,1, "2023-02-17", "Tenia los ojitos ratoniles, maliciosos. Sabia dilatarlos duramente o desmayarlos con recato o levantarlos con disimulo. Caminaba contoneando las imposibles caderas y era dificil, al verla.", "https://www.alberguescaminosantiago.com/wp-content/uploads/2018/02/Camino_de_Santiago_idicacion_poste_madera.jpg", 30, 0, "Camino de Santiago");
INSERT INTO events VALUES (default,1, "2023-02-17", "Tenia los ojitos ratoniles, maliciosos. Sabia dilatarlos duramente o desmayarlos con recato o levantarlos con disimulo. Caminaba contoneando las imposibles caderas y era dificil, al verla.", "https://pbs.twimg.com/media/FdSKUwgWIAEJNX0.jpg", 30, 0, "Messi");
INSERT INTO events VALUES (default,1, "2023-02-17", "Tenia los ojitos ratoniles, maliciosos. Sabia dilatarlos duramente o desmayarlos con recato o levantarlos con disimulo. Caminaba contoneando las imposibles caderas y era dificil, al verla.", "https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2023/03/13/16786897238945.jpg", 30, 0, "Oscars");
INSERT INTO events VALUES (default,1, "2023-02-17", "Tenia los ojitos ratoniles, maliciosos. Sabia dilatarlos duramente o desmayarlos con recato o levantarlos con disimulo. Caminaba contoneando las imposibles caderas y era dificil, al verla.", "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Sc%C3%A8ne_de_l%27op%C3%A9ra_Garnier.jpg/640px-Sc%C3%A8ne_de_l%27op%C3%A9ra_Garnier.jpg", 30, 0, "TEATRO");
INSERT INTO events VALUES (default,1, "2023-02-17", "Tenia los ojitos ratoniles, maliciosos. Sabia dilatarlos duramente o desmayarlos con recato o levantarlos con disimulo. Caminaba contoneando las imposibles caderas y era dificil, al verla.", "https://media.gettyimages.com/id/1361871457/es/foto/katy-perry-performs-onstage-during-katy-perry-play-las-vegas-residency-at-resorts-world-las.jpg?s=594x594&w=gi&k=20&c=uL9UM-2VExFHiFx-E2oUmMV4b4aYkpa4ZTQW_NAgZec=", 30, 0, "Concierto");
INSERT INTO users VALUES (default, "$2a$12$W9N8dguiW7gW8ITjrSXhBeJ2VMqwoyOI.TWXGNZ0DgY58.SXfQBxO", "ROLE_USER", "Diego");
INSERT INTO users VALUES (default, "$2a$12$dOVMKQy.uI26ruNy3XaVxeTsnan2Wzu07nCzcPu2wTwwMsbt/HKXS", "ROLE_USER", "Saul");
INSERT INTO users VALUES (default, "$2a$12$sG.OaNE3PskRYywjWbWiv.mMbFiP7Z0X1YvmG7Ob4DwE55gGFZ6gy", "ROLE_USER", "Johel");
INSERT INTO events VALUES (default,1, "2023-02-17", "concierto taburete", "url.jpg", 100, 0, "Taburete");
INSERT INTO events VALUES (default,1, "2023-06-01", "concierto rolling", "url.jpg", 500, 0, "Rolling");
INSERT INTO events VALUES (default,1, "2023-05-30", "concierto carol G", "url.jpg", 300, 0, "Carol G");
